<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.BulkExtensions.PostgreSql" Version="9.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Lumio.Balance">
      <HintPath>..\..\..\..\lumio-balance-system\src\Lumio.Balance\bin\Debug\net9.0\Lumio.Balance.dll</HintPath>
    </Reference>
    <Reference Include="Lumio.DataAccess">
      <HintPath>..\..\..\..\lumio-common\src\Lumio.DataAccess\bin\Debug\net9.0\Lumio.DataAccess.dll</HintPath>
    </Reference>
    <Reference Include="Lumio.Domain">
      <HintPath>..\..\..\..\lumio-common\src\Lumio.Domain\bin\Debug\net9.0\Lumio.Domain.dll</HintPath>
    </Reference>
    <Reference Include="Lumio.DomainServices">
      <HintPath>..\..\..\..\lumio-common\src\Lumio.DomainServices\bin\Debug\net9.0\Lumio.DomainServices.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
